name: Java Hello World

on:
  push:
    paths:
      - '**.java'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create HelloWorld.java
        run: |
          echo 'public class HelloWorld {
              public static void main(String[] args) {
                  System.out.println("Hello, world!");
              }
          }' > HelloWorld.java

      - name: Compile with JDK
        run: javac HelloWorld.java

      - name: Run with JRE
        run: java HelloWorld
